function D=DPoly(x,t,q0,order,numDim)
%%DPOLY The diffusion matrix for a continuous-time additive noise model in
%       numDim dimensions of motion with order moments of position whereby
%       the noise is only added to the highest-order derivatives of
%       position when used with a linear motion model. When order=1, this 
%       is the continuous white noise acceleration (CWNA) model. When
%       order=2, this is the continuous Wiener process acceleration model
%       (CWPA), also known as the white noise jerk model.
%
%INPUTS: x The target state(s). Only the second dimension is used to 
%          indicate the number of D matrices to be returned (the third
%          dimension of the D matrix, The basic additive noise model does
%          not depend on the target state. To be consistent with the other
%          parameters x should be a (order+1)*numDim X N, where N is the
%          number of D matrices on the output. If an empty matrix is
%          passed, then it is assumed only one output is desired.
%        t The time at which the diffusion matrix is desired. This is
%          unused, since the diffusion matrix in the basic additive noise
%          model is time-invariant. This is here so that DPoly can be used
%          with Runge-Kutta methods that expect the function to take two
%          arguments.
%       q0 The power spectral density of the noise for each dimension. If
%          the power spectral density of the noise is the same in all
%          dimensions, the a scalar q0 can be passed.
%    order The order >=0 of the filter. If order=1, then it is constant
%          velocity, 2 means constant acceleration, 3 means constant jerk,
%          etc. If this parameter is omitted, then order=1 is assumed.
%   numDim The number of dimensions of the simulation problem. If the
%          numDim parameter is omitted, then numDim=3 (3D motion) is
%          assumed.
%
%OUTPUT: D The diffusion matrix of a continuous-time linear additive noise
%          model where the noise is only added to the highest order terms
%          of the state. If the input x has multiple columns, then the same
%          number of copies of D are returned with D(:,:,i) being the ith
%          one.
%
%It is assumed that the state is ordered
%[position;velocity;acceleration;etc] for up to order moments of
%numDim-dimensional position. 
%
%Continuous-time additive noise models are discussed in more detail in [1].
%
%This diffusion matrix corresponds to the discrete-time process noise
%generated by the function QPolyKal.
%
%REFERENCES:
%[1] D. F. Crouse, "Basic tracking using nonlinear continuous-time dynamic
%    models," IEEE Aerospace and Electronic Systems Magazine, vol. 30, no.
%    2, Part II, pp. 4-41, Feb. 2015.
%
%October 2013 David F. Crouse, Naval Research Laboratory, Washington D.C.
%(UNCLASSIFIED) DISTRIBUTION STATEMENT A. Approved for public release.

    %The max allows the user to pass an empty matrix.
    numD=max(size(x,2),1);
    
    if(nargin<5||isempty(numDim))
        numDim=3;
    end
    
    if(nargin<4||isempty(order))
       order=1; 
    end
    
    if(isscalar(q0))
        q0=ones(numDim,1)*q0;
    end
    
    q0R=sqrt(q0);
    xDim=(order+1)*numDim;
    
    D=zeros(xDim,numDim);
    
    for curDim=1:numDim
        D((xDim-curDim+1),numDim-curDim+1)=q0R(numDim-curDim+1);
    end
    
    if(numD>1)
       D=repmat(D,[1,1,numD]); 
    end
end

%LICENSE:
%
%The source code is in the public domain and not licensed or under
%copyright. The information and software may be used freely by the public.
%As required by 17 U.S.C. 403, third parties producing copyrighted works
%consisting predominantly of the material produced by U.S. government
%agencies must provide notice with such work(s) identifying the U.S.
%Government material incorporated and stating that such material is not
%subject to copyright protection.
%
%Derived works shall not identify themselves in a manner that implies an
%endorsement by or an affiliation with the Naval Research Laboratory.
%
%RECIPIENT BEARS ALL RISK RELATING TO QUALITY AND PERFORMANCE OF THE
%SOFTWARE AND ANY RELATED MATERIALS, AND AGREES TO INDEMNIFY THE NAVAL
%RESEARCH LABORATORY FOR ALL THIRD-PARTY CLAIMS RESULTING FROM THE ACTIONS
%OF RECIPIENT IN THE USE OF THE SOFTWARE.
