function arr=unrankArrangement(rank,n,m)
%%UNRANKARRANGEMENT Return the arrangement n items put into m space
%                   corresponding to rank, where the first element of arr
%                   is the most significant. The ordering of the
%                   arrangements is not lexicographic, but is related to
%                   lexicographic ordering. Note that this function does
%                   not work for values of n where factorial(n) has a loss
%                   of precision, even if m is small.
%
%INPUTS: rank The rank of the arrangement counting from zero.
%           n The total number of items from which one draws.
%           m The number of slots into which these items can be placed.
%
%OUTPUTS: arr The length-m arrangement of the given rank when drawing from
%             n items, where the elements start from 1 (not 0).  If a rank
%             equal to or greater than the total number of unique
%             arrangements is given, then an empty matrix is returned.
%
%An arrangement of n numbers into m spaces is a subset of lexicographically
%ordered permutations. Thus, an arrangement of a particular rank can be
%generated by taking the most significant m elements of an appropriate
%permutation. Saying that the first m elements of the permutation of rank 0
%are the same as the first m elements of the arrangement of rank 0, values
%in the first m elements change with a change of (n-m)! in rank. There is a
%total of n!/(n-m)! arrangements. This can be computed as
%binomial(n,m)*factorial(m).
%
%Note that the function genAllArrangements will work for large values of n
%where this function might fail.
%
%September 2013 David F. Crouse, Naval Research Laboratory, Washington D.C.
%(UNCLASSIFIED) DISTRIBUTION STATEMENT A. Approved for public release.

    if(rank>=factorial(n)/factorial(n-m))
        arr=[];
        return;
    end

    permRank=factorial(n-m)*rank;
    permVal=unrankPermutation(permRank,n);
	arr=permVal(1:m);
end

%LICENSE:
%
%The source code is in the public domain and not licensed or under
%copyright. The information and software may be used freely by the public.
%As required by 17 U.S.C. 403, third parties producing copyrighted works
%consisting predominantly of the material produced by U.S. government
%agencies must provide notice with such work(s) identifying the U.S.
%Government material incorporated and stating that such material is not
%subject to copyright protection.
%
%Derived works shall not identify themselves in a manner that implies an
%endorsement by or an affiliation with the Naval Research Laboratory.
%
%RECIPIENT BEARS ALL RISK RELATING TO QUALITY AND PERFORMANCE OF THE
%SOFTWARE AND ANY RELATED MATERIALS, AND AGREES TO INDEMNIFY THE NAVAL
%RESEARCH LABORATORY FOR ALL THIRD-PARTY CLAIMS RESULTING FROM THE ACTIONS
%OF RECIPIENT IN THE USE OF THE SOFTWARE.
